---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Check ansible version !=2.7.0"
      assert:
        msg: "Ansible V2.7.0 can't be used until: https://github.com/ansible/ansible/issues/46600 is fixed"
        that:
          - ansible_version.string is version("2.7.0", "!=")
          - ansible_version.string is version("2.6.0", ">=")
      tags:
        - check
  vars:
    ansible_connection: local

- hosts: kube-master[0]
  tags:
    - k8s-unconf
  name: k8s deployment clean-up tasks
  become: yes
  gather_facts: false
  roles:
    - { role: kubespray-defaults}
  tasks:
    - include_tasks: tasks/k8s-deployment-unconfig.yml

