apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eph-delete
  labels:
    heritage: "manage-cluster"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eph-retain
  labels:
    heritage: "manage-cluster"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
